# Site settings
locale                   : "en-US"
title                    : "Patrick Hardin"
title_separator          : "-"
name                     : "Patrick Hardin"
description              : "Software Developer"
url                      : "https://www.phardin.com" 
baseurl                  : "" 
repository               : "patrick-hardin/patrick-hardin.github.io"

remote_theme             : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark"

twitter_username         : "PHardin_"
github_username          : "patrick-hardin"

reCaptcha:
  enabled                : true
  siteKey                : "6LddHpMUAAAAAOVQs4n69diA3rL5cXk_OLEJT_xy"
  secret                 : "6LddHpMUAAAAACQv3g6ghfe7Ct5je03f8HMvs6vN"

google_site_verification : "W9Cj58OidisYmuyKYJ_yfKitHTAkIbj0Exq8U9sjewU"
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Analytics
analytics:
  provider               : "google-gtag"
  google:
    tracking_id          : "UA-134971918-1"
    anonymize_ip         : false

# Site Author
author:
  name             : "Patrick Hardin"
  avatar           : "/assets/img/avatar.png"
  bio              : "Software Developer"
  location         : "Austin, TX"
  email            : "patrick@phardin.com"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/PHardin_"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/phardin.atx"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/patrickdhardin"
    - label: "GitHub"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/patrick-hardin"
    
# Site Footer
#footer:
#  links:
#    - label: ""
#      icon: "fab fa-fw fa-2x fa-twitter"
#      url: "https://twitter.com/PHardin_"
#    - label: ""
#      icon: "fab fa-fw fa-2x fa-facebook"
#      url: "https://facebook.com/phardin.atx"
#    - label: ""
#      icon: "fab fa-fw fa-2x fa-linkedin-in"
#      url: "https://www.linkedin.com/in/patrickdhardin"
#    - label: ""
#      icon: "fab fa-fw fa-2x fa-github"
#      url: "https://github.com/patrick-hardin"
   
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Outputting
permalink: pretty
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Chicago

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
